### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by seagoj** [jakewvincent/texmagic.nvim#4]
# issue

Nothing seems to happen when I edit or save. I have been expecting a PDF to get created in the .build directory, but nothing happens whether the .build dir is created or not. All the TeXMagic* functions seem to be responding as expected.

# installed versions

- **neovim**: v0.8.0-dev-696-g147cce29a
- **texlab**: 4.2.1
- **latexmk**: 4.77

# config

```lua
vim.g.tex_flavor = 'latex'

require('texmagic').setup{
	engines = {
		pdflatex = {
			executable = "latexmk",
			args = {
				"-pdflatex",
				"-interaction=nonstopmode",
				"-synctex=1",
				"-outdir=.build",
				"-pv",
				"%f"
			},
			isContinuous = false
		}
	}
}

require('lspconfig').texlab.setup{
	cmd = {"texlab"},
	filetypes = {"bib", "plaintex", "tex"},
	settings = {
		texlab = {
			rootDirectory = nil,
			build = _G.TexMagicBuildConfig,
			forwardSearch = {
				executable = "zathura",
				args = {"%p"}
			}
		}
	}
}
```

# test.tex
```latex
%! TEX plugin = TeXMagic.nvim
%! TEX program = pdflatex
\documentclass[a4paper]{article}

\begin{document}
	Hello world!
\end{document}

**Comment by jakewvincent** [comment]
If what you pasted is what you have in your config file, you need to capitalize the `x` in the global variable name :) (i.e. `_G.TeXMagicBuildConfig`). Let me know if that doesn't fix anything and I'll help troubleshoot.

**Comment by jakewvincent** [comment]
(You don't need the `%! TEX plugin = TeXMagic.nvim` that I see in your minimal example, btw. The title image in the readme is just written that way as a fun reference to the magic comments; it's possible that that is interfering with reading the `%! TEX program` comment. Sorry for the confusion there--)

**Comment by seagoj** [comment]
Ok, I've updated the files as described below, but I still don't get any errors or anything in .build. a `vim.inspect(_G.TeXMagicBuildConfig)` shows what I'd expect, so that's something.

# test.tex
```latex
%! TEX program = pdflatex
\documentclass[a4paper]{article}

\begin{document}
	Hello world!
\end{document}
```

# config
```lua

vim.g.tex_flavor = 'latex'

require('texmagic').setup{
	engines = {
		pdflatex = {
			executable = "latexmk",
			args = {
				"-pdflatex",
				"-interaction=nonstopmode",
				"-synctex=1",
				"-outdir=.build",
				"-pv",
				"%f"
			},
			isContinuous = false
		}
	}
}

require('lspconfig').texlab.setup{
	cmd = {"texlab"},
	filetypes = {"bib", "plaintex", "tex"},
	settings = {
		texlab = {
			rootDirectory = nil,
			build = _G.TeXMagicBuildConfig,
			forwardSearch = {
				executable = "zathura",
				args = {"%p"}
			}
		}
	}
}
```

**Comment by jakewvincent** [comment]
Do you get the expected behavior if you supply the contents of the `pdflatex` table in your TeXmagic build engine table directly into Texlab's settings?

```lua
vim.g.tex_flavor = 'latex'

require('texmagic').setup{
    engines = {
        --pdflatex = {}
    }
}

require('lspconfig').texlab.setup{
    cmd = {"texlab"},
    filetypes = {"bib", "plaintex", "tex"},
    settings = {
        texlab = {
            rootDirectory = nil,
            build = {
                executable = "latexmk",
                args = {
                    "-pdflatex",
                    "-interaction=nonstopmode",
                    "-synctex=1",
                    "-outdir=.build",
                    "-pv",
                    "%f"
                },
                isContinuous = false
            },
            forwardSearch = {
                executable = "zathura",
                args = {"%p"}
            }
        }
    }
}
```

**Comment by seagoj** [comment]
If I run the command suggested by the engine definition (`latexmk -pdflatex -interaction=nonstopmode -synctex=1 -outdir=.build -pv test.tex`), I do get a `.build/test.pdf` file, but it complains about not having `acroread` installed. Doesn't seem related, but I thought I'd share it.

I'll try the config suggestion and report back.

**Comment by seagoj** [comment]
Doesn't seem to make a difference if I use `_G.TeXMagicBuildConfig` or the hard-coded table

**Comment by seagoj** [comment]
It looks like if I add `onSave = true` to the hardcoded values then I get a `.build/test.pdf`

**Comment by seagoj** [comment]
so putting it all together, this config works:

```lua
vim.g.tex_flavor = 'latex'

require('texmagic').setup{
	engines = {
		pdflatex = {
			executable = "latexmk",
			args = {
				"-pdflatex",
				"-interaction=nonstopmode",
				"-synctex=1",
				"-outdir=.build",
				"-pv",
				"%f"
			},
			isContinuous = false,
			onSave = true
		}
	}
}

require('lspconfig').texlab.setup{
	cmd = {"texlab"},
	filetypes = {"bib", "plaintex", "tex"},
	settings = {
		texlab = {
			rootDirectory = nil,
			build = _G.TeXMagicBuildConfig,
			forwardSearch = {
				executable = "zathura",
				args = {"%p"}
			}
		}
	}
}
```

**Comment by seagoj** [comment]
Thanks for the help!

**Comment by jakewvincent** [comment]
Awesome. No prob!
